name: PhilippsPlugin
version: 1.9.2
api-version: 1.14
author: Joern19
main: minecraftserver.PhilippsPlugin
commands:
    TablistPrefix:
    HI:
    workbench:
    hit:
    home:
    setHome:
    rmHome:
    setRang:
    nick:
    stone:
    inv:
    enderinv:
    chestinv:
    changeName:  
    rucksack:
    enderchest:
    nick:
    freeze:
    msg:
    disablePlugin:
permissions:
    philippsPlugin.increasedFlySpeed:
        description: Allows Increased Flyspeed
        default: true
    philippsPlugin.colorCode:
        description: Allows the use of colorCode with &
        default: op